start_day: 1
start_month: 1
start_year: 1995
num_days: 365

zone_policy_map:
  -1: 
    Core_top:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Core_mid:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Core_bottom:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_top_ZN_3:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_top_ZN_2:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_top_ZN_1:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_top_ZN_4:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_bot_ZN_3:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_bot_ZN_2:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_bot_ZN_1:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_bot_ZN_4:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_mid_ZN_3:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_mid_ZN_2:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_mid_ZN_1:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455
    Perimeter_mid_ZN_4:
      policy: data/policy_libraries/policy_library_20220820/103_0_1e-1_2.pth
      init_log_std: -2.3025850929940455