# General Settings
building_name: Five Zone Building
building_idf_file: data/eplus_files/buildings/5ZoneAirCooled_electric.idf
weather_file: data/eplus_files/weather/USA_CO_Denver-Aurora-Buckley.AFB_.724695_TMY3.epw
num_zones: 5

observations:
  - outdoor temperature
  - site solar radiation
  - time
  - zone humidity
  - zone temperature
  - occupancy

timesteps_per_hour: 4

# max_energy_consumption: 57561696.237888955
# min_energy_consumption: 17976704.46193411

# Building Settings
available_zones:
  - Core_ZN
  - Perimeter_ZN_1
  - Perimeter_ZN_2
  - Perimeter_ZN_3
  - Perimeter_ZN_4

airloops:
  Core_ZN: PSZ-AC:1
  Perimeter_ZN_1: PSZ-AC:2
  Perimeter_ZN_2: PSZ-AC:3
  Perimeter_ZN_3: PSZ-AC:4
  Perimeter_ZN_4: PSZ-AC:5
